name: 'Coupling Contribution Action'
description: 'This action will send contribution information to Coupling when invoked.'
inputs:
  coupling-secret:
    description: 'A coupling secret for a party is required in order to update contributions.'
    required: true
  party-id:
    description: 'A coupling secret for a party is required in order to update contributions.'
    required: true
  contribution-file:
    description: 'A JSON containing the contribution information'
    required: true
  cli-type:
    description: 'CLI runtime type to use'
    default: 'js'
    required: false
  save-contribution:
    description: 'Should save contribution'
    default: 'true'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Coupling CLI (Java)
      if: ${{ inputs.cli-type == 'jvm' }}
      shell: bash
      run: |-
        mkdir ~/.coupling
        wget -c https://coupling.zegreatrob.com/latest-cli -O - | tar -xz --directory ~/.coupling
        echo "~/.coupling/coupling-cli/bin" >> $GITHUB_PATH
    - name: Install Coupling CLI (JS)
      if: ${{ inputs.cli-type == 'js' }}
      shell: bash
      run: |-
        mkdir -p ~/.coupling/coupling-cli-js
        wget -c "https://coupling.zegreatrob.com/latest-cli?type=js" -O - | tar -xz --directory ~/.coupling/coupling-cli-js
        cd ~/.coupling/coupling-cli-js
        npm install
        npm link
    - name: Show Input File
      shell: bash
      run: awk 1 ${{ inputs.contribution-file }}
    - name: Verify Connectivity
      env:
        COUPLING_CLI_ACCESS_TOKEN: ${{ inputs.coupling-secret }}
      run: coupling party list
      shell: bash
    - shell: bash
      run: awk 1 ${{ inputs.contribution-file }} | cat
    - name: Save Contribution
      if: ${{ inputs.save-contribution == 'true' }}
      env:
        COUPLING_CLI_ACCESS_TOKEN: ${{ inputs.coupling-secret }}
      run: awk 1 ${{ inputs.contribution-file }} | coupling party contribution --party-id ${{ inputs.party-id }} save
      shell: bash
    - name: Uninstall Coupling CLI
      shell: bash
      run: rm -r ~/.coupling
