name: 'Coupling Contribution Action'
description: 'This action will send contribution information to Coupling when invoked.'
inputs:
  coupling-secret:
    description: 'A coupling secret for a party is required in order to update contributions.'
    required: true
  party-id:
    description: 'A coupling secret for a party is required in order to update contributions.'
    required: true
  contribution-file:
    description: 'A JSON containing the contribution information'
    required: true
  cli-type:
    description: 'A JSON containing the contribution information'
    default: 'jvm'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Coupling CLI
      shell: bash
      run: |- 
        mkdir ~/.coupling
        wget -c https://coupling.zegreatrob.com/latest-cli -O - | tar -xz --directory ~/.coupling
        echo "~/.coupling/coupling-cli/bin" >> $GITHUB_PATH
    - name: Save Contribution
      env:
        COUPLING_CLI_ACCESS_TOKEN: ${{ inputs.coupling-secret }}
      run: cat ${{ inputs.contribution-file }} | coupling party contribution --party-id ${{ inputs.party-id }} save
      shell: bash
    - name: Uninstall Coupling CLI
      shell: bash
      run: rm -r ~/.coupling
