name: 'Coupling Contribution Action'
description: 'This action will send contribution information to Coupling when invoked.'
inputs:
  coupling-secret:
    description: 'A coupling secret for a party is required in order to update contributions.'
    required: true
  party-id:
    description: 'A coupling secret for a party is required in order to update contributions.'
    required: true
  contribution-file:
    description: 'A JSON containing the contribution information'
    required: true
  cli-type:
    description: 'CLI runtime type to use'
    default: 'js'
    required: false
  link:
    description: 'Optional link to include to relate to the contribution. If omitted, will link to commit in github.'
    default: ''
    required: false
  save-contribution:
    description: 'Should save contribution'
    default: 'true'
    required: false
  cycle-time-from-first-commit:
    description: 'should calculate cycle time by subtracting the current time from the first commit time'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Coupling CLI (Java)
      if: ${{ inputs.cli-type == 'jvm' }}
      shell: bash
      run: |-
        mkdir ~/.coupling
        wget -c https://coupling.zegreatrob.com/latest-cli -O - | tar -xz --directory ~/.coupling
        echo "~/.coupling/coupling-cli/bin" >> $GITHUB_PATH
    - name: Install Coupling CLI (JS)
      if: ${{ inputs.cli-type == 'js' }}
      shell: bash
      run: |-
        mkdir -p ~/.coupling/coupling-cli-js
        wget -c "https://coupling.zegreatrob.com/latest-cli?type=js" -O - | tar -xz --directory ~/.coupling/coupling-cli-js
        cd ~/.coupling/coupling-cli-js
        npm install
        npm link
    - name: Verify Connectivity
      shell: bash
      env:
        COUPLING_CLI_ACCESS_TOKEN: ${{ inputs.coupling-secret }}
      run: coupling party list
    - name: Create Link to Github
      if: "${{ github.event.inputs.link == '' }}"
      shell: bash
      run: echo "CONTRIBUTION_GITHUB_LINK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$(cat ${{ inputs.contribution-file }} | jq  -r .lastCommit)" >> "$GITHUB_ENV"
    - name: Include Link
      if: "${{ github.event.inputs.link != '' }}"
      shell: bash
      run: echo "CONTRIBUTION_GITHUB_LINK=${{ github.event.inputs.link }}" >> "$GITHUB_ENV"
    - name: Enable Cycle Time From First Commit
      if: "${{ inputs.cycle-time-from-first-commit  == 'true' }}"
      shell: bash
      run: echo "CYCLE_TIME_FROM_FIRST_COMMIT=--cycle-time-from-first-commit=" >> "$GITHUB_ENV"
    - name: Show Input File
      shell: bash
      run: awk 1 ${{ inputs.contribution-file }}
    - name: Save Contribution
      shell: bash
      if: ${{ inputs.save-contribution == 'true' }}
      env:
        COUPLING_CLI_ACCESS_TOKEN: ${{ inputs.coupling-secret }}
      run: coupling party contribution --party-id ${{ inputs.party-id }} save --link $CONTRIBUTION_GITHUB_LINK $CYCLE_TIME_FROM_FIRST_COMMIT --input-json "$(cat ${{ inputs.contribution-file }})"
    - name: Uninstall Coupling CLI
      shell: bash
      run: rm -r ~/.coupling
